export const mask: string;
export const box: string;
export const title: string;
export const noTitle: string;
export const content: string;
export const children: string;
export const buttons: string;
export const button: string;
export const primary: string;
